apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokemon-api-chart.fullname" . }}
  labels:
    {{- include "pokemon-api-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pokemon-api-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pokemon-api-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: pokemon-scanner
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sleep", "infinity" ]  # Keeps the container running without executing the script
          resources: {}
      restartPolicy: Always

