apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokemon-api-chart.fullname" . }}
  labels:
    {{- include "pokemon-api-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "pokemon-api-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP

