image:
  repository: chethantk/pokemon-scanner-alpine
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP  
  port: 8080

ingress:
  enabled: false  


serviceAccount:
  create: true  

autoscaling:
  enabled: false  

